
pipelines:
  - name: cloud_run_deploy
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
            tag: "latest"
    steps:
    - name: gcloud_deploy_frontend
      type: Bash
      configuration:
        integrations:
          - name: gcpsa
      execution:
        onExecute:
        - gcloud config list


