
pipelines:
  - name: cloud_run_deploy
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
            tag: "latest"
    steps:
    - name: gcloud_deploy_frontend
      type: Bash
      configuration:
        integrations:
          - name: gcp_login
      execution:
        onExecute:
        - printenv $int_gcp_login_jsonkey > /tmp/json.key
        - gcloud auth activate-service-account $int_gcp_login_user --key-file /tmp/json.key
        - gcloud config set project $int_gcp_login_project


