apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.3
        ports:
          - containerPort: 3550
            name: h2c
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi